/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Models.Petugas;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import java.util.Date;
import javafx.concurrent.Task;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IPutuAdi
 */
public class InputPetugas extends javax.swing.JFrame {

    /**
     * Creates new form InputPetugas
     */
    public InputPetugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDasar = new javax.swing.JPanel();
        input = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfIdPetugas = new javax.swing.JTextField();
        tfAlamatPetugas = new javax.swing.JTextField();
        tfNoHPPetugas = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtNmPetugas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPetugas = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDasar.setLayout(new java.awt.CardLayout());

        jLabel1.setText("ID Petugas");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("No HP");

        btnAdd.setText("Simpan");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        tbPetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbPetugas);

        btnDelete.setText("Delete");

        javax.swing.GroupLayout inputLayout = new javax.swing.GroupLayout(input);
        input.setLayout(inputLayout);
        inputLayout.setHorizontalGroup(
            inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfIdPetugas)
                    .addComponent(tfAlamatPetugas)
                    .addComponent(tfNoHPPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtNmPetugas))
                .addGap(18, 18, 18)
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        inputLayout.setVerticalGroup(
            inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfIdPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete)))
                .addGap(18, 18, 18)
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNmPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addGap(18, 18, 18)
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAlamatPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNoHPPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        panelDasar.add(input, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDasar, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDasar, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    public JTextField getTxtNmPetugas() {
        return txtNmPetugas;
    }

    public void setTxtNmPetugas(JTextField txtNmPetugas) {
        this.txtNmPetugas = txtNmPetugas;
    }

    
    
    public JButton getBtnAdd() {
        return btnAdd;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }

    public void setIdPetugas(String s) {
        tfIdPetugas.setText(s);
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }   
    
    public void setNoHPPetugas(String s) {
        tfNoHPPetugas.setText(s);
    }

    public JTextField getTfIdPetugas() {
        return tfIdPetugas;
    }

    public void setTfIdPetugas(JTextField tfIdPetugas) {
        this.tfIdPetugas = tfIdPetugas;
    }

    public JTextField getTfNoHPPetugas() {
        return tfNoHPPetugas;
    }

    public void setTfNoHPPetugas(JTextField tfNoHPPetugas) {
        this.tfNoHPPetugas = tfNoHPPetugas;
    }

    public String getAlamatPetugas() {
        return tfAlamatPetugas.getText();
    }

    public void setAlamatPetugas(String s) {
        tfAlamatPetugas.setText(s);
    }
    public JTextField getTfAlamatPetugas() {
        return tfAlamatPetugas;
    }

    public String getIdPetugas() {
        return tfIdPetugas.getText();
    }

    public String getNoHPPetugas() {
        return tfNoHPPetugas.getText();
    }
 public void addListener(ActionListener e){
        btnAdd.addActionListener(e);
        btnEdit.addActionListener(e);
    }

    public void addAdapter(MouseAdapter e) {
        tbPetugas.addMouseListener(e);
    }
 
    public void viewAll(ArrayList<Petugas> list) {
        String[] title = {"Id Petugas","Nama Petugas","Alamat Petugas","No HP Petugas"};
        String[][] data = new String[list.size()][4];
        for (int i = 0; i < list.size(); i++) {
            Petugas p = list.get(i);
            data[i][0] = p.getIdPetugas();
            data[i][1] = p.getNama();
            data[i][2] = p.getAlamat();
            data[i][3] = p.getNoHP();
        }
        tbPetugas.setModel(new DefaultTableModel(data,title));
    }
    
    public void showMessage(Component  c, String s){
        JOptionPane.showMessageDialog(c, s);
    }

    public JTable getTbPetugas() {
        return tbPetugas;
    }
    public void view (Petugas p) {
        tfIdPetugas.setText(p.getIdPetugas());
        txtNmPetugas.setText(p.getNama());
        tfAlamatPetugas.setText(p.getAlamat());
        tfNoHPPetugas.setText(p.getNoHP());
        btnAdd.setVisible(false);
        btnEdit.setVisible(true);
    }
    public void reset() {
        tfIdPetugas.setText("");
        txtNmPetugas.setText("");
        tfAlamatPetugas.setText("");
        tfNoHPPetugas.setText("");
        btnAdd.setVisible(true);
        btnEdit.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDasar;
    private javax.swing.JTable tbPetugas;
    private javax.swing.JTextField tfAlamatPetugas;
    private javax.swing.JTextField tfIdPetugas;
    private javax.swing.JTextField tfNoHPPetugas;
    private javax.swing.JTextField txtNmPetugas;
    // End of variables declaration//GEN-END:variables
}
